//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLMobileAppApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTRANINFO
    {
        public long ID { get; set; }
        public long ACID { get; set; }
        public System.DateTime TRANDATE { get; set; }
        public string TRANNO { get; set; }
        public string TRANTYPE { get; set; }
        public decimal TRANAMOUNT { get; set; }
    
        public virtual APPACINFO APPACINFO { get; set; }
    }
}
