//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLMobileAppApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPCREDITCARDINFO
    {
        public long ID { get; set; }
        public long USERID { get; set; }
        public string CCARDNO { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
    
        public virtual APPUSER APPUSER { get; set; }
    }
}
