//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLMobileAppApi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OBLAPPEntities : DbContext
    {
        public OBLAPPEntities()
            : base("name=OBLAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APPUSER> APPUSERs { get; set; }
        public DbSet<ACTRANINFO> ACTRANINFOes { get; set; }
        public DbSet<APPACINFO> APPACINFOes { get; set; }
        public DbSet<APPCUSTINFO> APPCUSTINFOes { get; set; }
        public DbSet<APPCREDITCARDINFO> APPCREDITCARDINFOes { get; set; }
        public DbSet<CARDDETAILINFO> CARDDETAILINFOes { get; set; }
        public DbSet<APPUSERLOG> APPUSERLOGs { get; set; }
    }
}
