//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLMobileAppApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUSERLOG
    {
        public long ID { get; set; }
        public string DEVICEID { get; set; }
        public string MOBILENO { get; set; }
        public long USERID { get; set; }
        public string OTP { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> LOGTIME { get; set; }
    
        public virtual APPUSER APPUSER { get; set; }
    }
}
