//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLMobileAppApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUSER
    {
        public APPUSER()
        {
            this.APPACINFOes = new HashSet<APPACINFO>();
            this.APPCUSTINFOes = new HashSet<APPCUSTINFO>();
            this.APPCREDITCARDINFOes = new HashSet<APPCREDITCARDINFO>();
            this.APPUSERLOGs = new HashSet<APPUSERLOG>();
        }
    
        public long ID { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string MOBILENO { get; set; }
        public bool ISACTIVE { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
    
        public virtual ICollection<APPACINFO> APPACINFOes { get; set; }
        public virtual ICollection<APPCUSTINFO> APPCUSTINFOes { get; set; }
        public virtual ICollection<APPCREDITCARDINFO> APPCREDITCARDINFOes { get; set; }
        public virtual ICollection<APPUSERLOG> APPUSERLOGs { get; set; }
    }
}
