//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLMobileAppApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDDETAILINFO
    {
        public string CARDNO { get; set; }
        public string MASKCARDNO { get; set; }
        public string CLIENTNAME { get; set; }
        public string ADDRESS { get; set; }
        public string PAYMENTDATE { get; set; }
        public long ID { get; set; }
        public int STNO { get; set; }
        public System.DateTime BILLINGDATE { get; set; }
        public string CURRENCY { get; set; }
        public decimal CREDITLIMIT { get; set; }
        public decimal AVAILABLECRLIMIT { get; set; }
        public decimal CASHLIMIT { get; set; }
        public decimal AVAILABLECASHLIMIT { get; set; }
        public decimal MINAMNTDUE { get; set; }
        public decimal PREVBALANCE { get; set; }
        public decimal CURRBALANCE { get; set; }
        public decimal TOTALPURCHASE { get; set; }
        public decimal TOTALINTR { get; set; }
        public decimal PAYMENTS { get; set; }
        public decimal CREDITS { get; set; }
        public Nullable<decimal> CASHADV { get; set; }
        public long STID { get; set; }
    }
}
