//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OBLMobileAppApi.OracleDBService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OradbaccessSoap", Namespace="http://tempuri.org/")]
    public partial class Oradbaccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCCardDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLankaBanglaFOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLankaBanglaFDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHBInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLankaBanglaFVisaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLankaBanglaFMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetONEBankVisaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRJSCTranOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRJSCTranDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRJSCTranDateRangeNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLCARTranOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLCMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCifsDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPHTranOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCTRTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCTRAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCTRAccountDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCTRSignatoryDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCTRIndividualAccDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBalanceaccsrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustAccTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustAccNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustAccTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountDetailForBATOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGPDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGPDataAccOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Oradbaccess() {
            this.Url = global::OBLMobileAppApi.Properties.Settings.Default.OBLMobileAppApi_OracleDBService_Oradbaccess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetCCardDetailCompletedEventHandler GetCCardDetailCompleted;
        
        /// <remarks/>
        public event GetLankaBanglaFCompletedEventHandler GetLankaBanglaFCompleted;
        
        /// <remarks/>
        public event GetLankaBanglaFDateRangeCompletedEventHandler GetLankaBanglaFDateRangeCompleted;
        
        /// <remarks/>
        public event GetRateCompletedEventHandler GetRateCompleted;
        
        /// <remarks/>
        public event GetHBInfoCompletedEventHandler GetHBInfoCompleted;
        
        /// <remarks/>
        public event GetLankaBanglaFVisaCompletedEventHandler GetLankaBanglaFVisaCompleted;
        
        /// <remarks/>
        public event GetLankaBanglaFMoneyCompletedEventHandler GetLankaBanglaFMoneyCompleted;
        
        /// <remarks/>
        public event GetONEBankVisaCompletedEventHandler GetONEBankVisaCompleted;
        
        /// <remarks/>
        public event GetRJSCTranCompletedEventHandler GetRJSCTranCompleted;
        
        /// <remarks/>
        public event GetRJSCTranDateRangeCompletedEventHandler GetRJSCTranDateRangeCompleted;
        
        /// <remarks/>
        public event GetRJSCTranDateRangeNewCompletedEventHandler GetRJSCTranDateRangeNewCompleted;
        
        /// <remarks/>
        public event GetLCARTranCompletedEventHandler GetLCARTranCompleted;
        
        /// <remarks/>
        public event GetLCMasterCompletedEventHandler GetLCMasterCompleted;
        
        /// <remarks/>
        public event GetCifsDetailCompletedEventHandler GetCifsDetailCompleted;
        
        /// <remarks/>
        public event GetPHTranCompletedEventHandler GetPHTranCompleted;
        
        /// <remarks/>
        public event GetCTRTransactionCompletedEventHandler GetCTRTransactionCompleted;
        
        /// <remarks/>
        public event GetCTRAccountCompletedEventHandler GetCTRAccountCompleted;
        
        /// <remarks/>
        public event GetCTRAccountDetailCompletedEventHandler GetCTRAccountDetailCompleted;
        
        /// <remarks/>
        public event GetCTRSignatoryDetailCompletedEventHandler GetCTRSignatoryDetailCompleted;
        
        /// <remarks/>
        public event GetCTRIndividualAccDetailCompletedEventHandler GetCTRIndividualAccDetailCompleted;
        
        /// <remarks/>
        public event GetBalanceaccsrCompletedEventHandler GetBalanceaccsrCompleted;
        
        /// <remarks/>
        public event GetCustAccTransactionsCompletedEventHandler GetCustAccTransactionsCompleted;
        
        /// <remarks/>
        public event GetCustAccNameCompletedEventHandler GetCustAccNameCompleted;
        
        /// <remarks/>
        public event GetCustAccTypeCompletedEventHandler GetCustAccTypeCompleted;
        
        /// <remarks/>
        public event GetAccountDetailForBATCompletedEventHandler GetAccountDetailForBATCompleted;
        
        /// <remarks/>
        public event GetGPDataCompletedEventHandler GetGPDataCompleted;
        
        /// <remarks/>
        public event GetGPDataAccCompletedEventHandler GetGPDataAccCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCCardDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCCardDetail(string cardno) {
            object[] results = this.Invoke("GetCCardDetail", new object[] {
                        cardno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCCardDetailAsync(string cardno) {
            this.GetCCardDetailAsync(cardno, null);
        }
        
        /// <remarks/>
        public void GetCCardDetailAsync(string cardno, object userState) {
            if ((this.GetCCardDetailOperationCompleted == null)) {
                this.GetCCardDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCCardDetailOperationCompleted);
            }
            this.InvokeAsync("GetCCardDetail", new object[] {
                        cardno}, this.GetCCardDetailOperationCompleted, userState);
        }
        
        private void OnGetCCardDetailOperationCompleted(object arg) {
            if ((this.GetCCardDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCCardDetailCompleted(this, new GetCCardDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLankaBanglaF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLankaBanglaF(string lngData, System.DateTime sysdate) {
            object[] results = this.Invoke("GetLankaBanglaF", new object[] {
                        lngData,
                        sysdate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLankaBanglaFAsync(string lngData, System.DateTime sysdate) {
            this.GetLankaBanglaFAsync(lngData, sysdate, null);
        }
        
        /// <remarks/>
        public void GetLankaBanglaFAsync(string lngData, System.DateTime sysdate, object userState) {
            if ((this.GetLankaBanglaFOperationCompleted == null)) {
                this.GetLankaBanglaFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLankaBanglaFOperationCompleted);
            }
            this.InvokeAsync("GetLankaBanglaF", new object[] {
                        lngData,
                        sysdate}, this.GetLankaBanglaFOperationCompleted, userState);
        }
        
        private void OnGetLankaBanglaFOperationCompleted(object arg) {
            if ((this.GetLankaBanglaFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLankaBanglaFCompleted(this, new GetLankaBanglaFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLankaBanglaFDateRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLankaBanglaFDateRange(string lngData, System.DateTime sysdate, System.DateTime to_date) {
            object[] results = this.Invoke("GetLankaBanglaFDateRange", new object[] {
                        lngData,
                        sysdate,
                        to_date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLankaBanglaFDateRangeAsync(string lngData, System.DateTime sysdate, System.DateTime to_date) {
            this.GetLankaBanglaFDateRangeAsync(lngData, sysdate, to_date, null);
        }
        
        /// <remarks/>
        public void GetLankaBanglaFDateRangeAsync(string lngData, System.DateTime sysdate, System.DateTime to_date, object userState) {
            if ((this.GetLankaBanglaFDateRangeOperationCompleted == null)) {
                this.GetLankaBanglaFDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLankaBanglaFDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetLankaBanglaFDateRange", new object[] {
                        lngData,
                        sysdate,
                        to_date}, this.GetLankaBanglaFDateRangeOperationCompleted, userState);
        }
        
        private void OnGetLankaBanglaFDateRangeOperationCompleted(object arg) {
            if ((this.GetLankaBanglaFDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLankaBanglaFDateRangeCompleted(this, new GetLankaBanglaFDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRate(string strCurrency) {
            object[] results = this.Invoke("GetRate", new object[] {
                        strCurrency});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRateAsync(string strCurrency) {
            this.GetRateAsync(strCurrency, null);
        }
        
        /// <remarks/>
        public void GetRateAsync(string strCurrency, object userState) {
            if ((this.GetRateOperationCompleted == null)) {
                this.GetRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRateOperationCompleted);
            }
            this.InvokeAsync("GetRate", new object[] {
                        strCurrency}, this.GetRateOperationCompleted, userState);
        }
        
        private void OnGetRateOperationCompleted(object arg) {
            if ((this.GetRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRateCompleted(this, new GetRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHBInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHBInfo(string stracc) {
            object[] results = this.Invoke("GetHBInfo", new object[] {
                        stracc});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHBInfoAsync(string stracc) {
            this.GetHBInfoAsync(stracc, null);
        }
        
        /// <remarks/>
        public void GetHBInfoAsync(string stracc, object userState) {
            if ((this.GetHBInfoOperationCompleted == null)) {
                this.GetHBInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHBInfoOperationCompleted);
            }
            this.InvokeAsync("GetHBInfo", new object[] {
                        stracc}, this.GetHBInfoOperationCompleted, userState);
        }
        
        private void OnGetHBInfoOperationCompleted(object arg) {
            if ((this.GetHBInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHBInfoCompleted(this, new GetHBInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLankaBanglaFVisa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLankaBanglaFVisa(string lngData, System.DateTime sysdate) {
            object[] results = this.Invoke("GetLankaBanglaFVisa", new object[] {
                        lngData,
                        sysdate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLankaBanglaFVisaAsync(string lngData, System.DateTime sysdate) {
            this.GetLankaBanglaFVisaAsync(lngData, sysdate, null);
        }
        
        /// <remarks/>
        public void GetLankaBanglaFVisaAsync(string lngData, System.DateTime sysdate, object userState) {
            if ((this.GetLankaBanglaFVisaOperationCompleted == null)) {
                this.GetLankaBanglaFVisaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLankaBanglaFVisaOperationCompleted);
            }
            this.InvokeAsync("GetLankaBanglaFVisa", new object[] {
                        lngData,
                        sysdate}, this.GetLankaBanglaFVisaOperationCompleted, userState);
        }
        
        private void OnGetLankaBanglaFVisaOperationCompleted(object arg) {
            if ((this.GetLankaBanglaFVisaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLankaBanglaFVisaCompleted(this, new GetLankaBanglaFVisaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLankaBanglaFMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLankaBanglaFMoney(string lngData, System.DateTime sysdate) {
            object[] results = this.Invoke("GetLankaBanglaFMoney", new object[] {
                        lngData,
                        sysdate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLankaBanglaFMoneyAsync(string lngData, System.DateTime sysdate) {
            this.GetLankaBanglaFMoneyAsync(lngData, sysdate, null);
        }
        
        /// <remarks/>
        public void GetLankaBanglaFMoneyAsync(string lngData, System.DateTime sysdate, object userState) {
            if ((this.GetLankaBanglaFMoneyOperationCompleted == null)) {
                this.GetLankaBanglaFMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLankaBanglaFMoneyOperationCompleted);
            }
            this.InvokeAsync("GetLankaBanglaFMoney", new object[] {
                        lngData,
                        sysdate}, this.GetLankaBanglaFMoneyOperationCompleted, userState);
        }
        
        private void OnGetLankaBanglaFMoneyOperationCompleted(object arg) {
            if ((this.GetLankaBanglaFMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLankaBanglaFMoneyCompleted(this, new GetLankaBanglaFMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetONEBankVisa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetONEBankVisa(string lngData) {
            object[] results = this.Invoke("GetONEBankVisa", new object[] {
                        lngData});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetONEBankVisaAsync(string lngData) {
            this.GetONEBankVisaAsync(lngData, null);
        }
        
        /// <remarks/>
        public void GetONEBankVisaAsync(string lngData, object userState) {
            if ((this.GetONEBankVisaOperationCompleted == null)) {
                this.GetONEBankVisaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetONEBankVisaOperationCompleted);
            }
            this.InvokeAsync("GetONEBankVisa", new object[] {
                        lngData}, this.GetONEBankVisaOperationCompleted, userState);
        }
        
        private void OnGetONEBankVisaOperationCompleted(object arg) {
            if ((this.GetONEBankVisaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetONEBankVisaCompleted(this, new GetONEBankVisaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRJSCTran", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRJSCTran(string strKey, string lngData, System.DateTime sysdate) {
            object[] results = this.Invoke("GetRJSCTran", new object[] {
                        strKey,
                        lngData,
                        sysdate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRJSCTranAsync(string strKey, string lngData, System.DateTime sysdate) {
            this.GetRJSCTranAsync(strKey, lngData, sysdate, null);
        }
        
        /// <remarks/>
        public void GetRJSCTranAsync(string strKey, string lngData, System.DateTime sysdate, object userState) {
            if ((this.GetRJSCTranOperationCompleted == null)) {
                this.GetRJSCTranOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRJSCTranOperationCompleted);
            }
            this.InvokeAsync("GetRJSCTran", new object[] {
                        strKey,
                        lngData,
                        sysdate}, this.GetRJSCTranOperationCompleted, userState);
        }
        
        private void OnGetRJSCTranOperationCompleted(object arg) {
            if ((this.GetRJSCTranCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRJSCTranCompleted(this, new GetRJSCTranCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRJSCTranDateRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRJSCTranDateRange(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date) {
            object[] results = this.Invoke("GetRJSCTranDateRange", new object[] {
                        strKey,
                        lngData,
                        sysdate,
                        to_date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRJSCTranDateRangeAsync(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date) {
            this.GetRJSCTranDateRangeAsync(strKey, lngData, sysdate, to_date, null);
        }
        
        /// <remarks/>
        public void GetRJSCTranDateRangeAsync(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date, object userState) {
            if ((this.GetRJSCTranDateRangeOperationCompleted == null)) {
                this.GetRJSCTranDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRJSCTranDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetRJSCTranDateRange", new object[] {
                        strKey,
                        lngData,
                        sysdate,
                        to_date}, this.GetRJSCTranDateRangeOperationCompleted, userState);
        }
        
        private void OnGetRJSCTranDateRangeOperationCompleted(object arg) {
            if ((this.GetRJSCTranDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRJSCTranDateRangeCompleted(this, new GetRJSCTranDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRJSCTranDateRangeNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRJSCTranDateRangeNew(string strKey, long lngData, string sysdate, string to_date) {
            object[] results = this.Invoke("GetRJSCTranDateRangeNew", new object[] {
                        strKey,
                        lngData,
                        sysdate,
                        to_date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRJSCTranDateRangeNewAsync(string strKey, long lngData, string sysdate, string to_date) {
            this.GetRJSCTranDateRangeNewAsync(strKey, lngData, sysdate, to_date, null);
        }
        
        /// <remarks/>
        public void GetRJSCTranDateRangeNewAsync(string strKey, long lngData, string sysdate, string to_date, object userState) {
            if ((this.GetRJSCTranDateRangeNewOperationCompleted == null)) {
                this.GetRJSCTranDateRangeNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRJSCTranDateRangeNewOperationCompleted);
            }
            this.InvokeAsync("GetRJSCTranDateRangeNew", new object[] {
                        strKey,
                        lngData,
                        sysdate,
                        to_date}, this.GetRJSCTranDateRangeNewOperationCompleted, userState);
        }
        
        private void OnGetRJSCTranDateRangeNewOperationCompleted(object arg) {
            if ((this.GetRJSCTranDateRangeNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRJSCTranDateRangeNewCompleted(this, new GetRJSCTranDateRangeNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLCARTran", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLCARTran(string lngData) {
            object[] results = this.Invoke("GetLCARTran", new object[] {
                        lngData});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLCARTranAsync(string lngData) {
            this.GetLCARTranAsync(lngData, null);
        }
        
        /// <remarks/>
        public void GetLCARTranAsync(string lngData, object userState) {
            if ((this.GetLCARTranOperationCompleted == null)) {
                this.GetLCARTranOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLCARTranOperationCompleted);
            }
            this.InvokeAsync("GetLCARTran", new object[] {
                        lngData}, this.GetLCARTranOperationCompleted, userState);
        }
        
        private void OnGetLCARTranOperationCompleted(object arg) {
            if ((this.GetLCARTranCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLCARTranCompleted(this, new GetLCARTranCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLCMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLCMaster() {
            object[] results = this.Invoke("GetLCMaster", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLCMasterAsync() {
            this.GetLCMasterAsync(null);
        }
        
        /// <remarks/>
        public void GetLCMasterAsync(object userState) {
            if ((this.GetLCMasterOperationCompleted == null)) {
                this.GetLCMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLCMasterOperationCompleted);
            }
            this.InvokeAsync("GetLCMaster", new object[0], this.GetLCMasterOperationCompleted, userState);
        }
        
        private void OnGetLCMasterOperationCompleted(object arg) {
            if ((this.GetLCMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLCMasterCompleted(this, new GetLCMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCifsDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCifsDetail() {
            object[] results = this.Invoke("GetCifsDetail", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCifsDetailAsync() {
            this.GetCifsDetailAsync(null);
        }
        
        /// <remarks/>
        public void GetCifsDetailAsync(object userState) {
            if ((this.GetCifsDetailOperationCompleted == null)) {
                this.GetCifsDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCifsDetailOperationCompleted);
            }
            this.InvokeAsync("GetCifsDetail", new object[0], this.GetCifsDetailOperationCompleted, userState);
        }
        
        private void OnGetCifsDetailOperationCompleted(object arg) {
            if ((this.GetCifsDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCifsDetailCompleted(this, new GetCifsDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPHTran", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPHTran(string lngData, System.DateTime sysdate) {
            object[] results = this.Invoke("GetPHTran", new object[] {
                        lngData,
                        sysdate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPHTranAsync(string lngData, System.DateTime sysdate) {
            this.GetPHTranAsync(lngData, sysdate, null);
        }
        
        /// <remarks/>
        public void GetPHTranAsync(string lngData, System.DateTime sysdate, object userState) {
            if ((this.GetPHTranOperationCompleted == null)) {
                this.GetPHTranOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPHTranOperationCompleted);
            }
            this.InvokeAsync("GetPHTran", new object[] {
                        lngData,
                        sysdate}, this.GetPHTranOperationCompleted, userState);
        }
        
        private void OnGetPHTranOperationCompleted(object arg) {
            if ((this.GetPHTranCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPHTranCompleted(this, new GetPHTranCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCTRTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCTRTransaction(string strAcno, System.DateTime dtFrom, System.DateTime dtTo) {
            object[] results = this.Invoke("GetCTRTransaction", new object[] {
                        strAcno,
                        dtFrom,
                        dtTo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCTRTransactionAsync(string strAcno, System.DateTime dtFrom, System.DateTime dtTo) {
            this.GetCTRTransactionAsync(strAcno, dtFrom, dtTo, null);
        }
        
        /// <remarks/>
        public void GetCTRTransactionAsync(string strAcno, System.DateTime dtFrom, System.DateTime dtTo, object userState) {
            if ((this.GetCTRTransactionOperationCompleted == null)) {
                this.GetCTRTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCTRTransactionOperationCompleted);
            }
            this.InvokeAsync("GetCTRTransaction", new object[] {
                        strAcno,
                        dtFrom,
                        dtTo}, this.GetCTRTransactionOperationCompleted, userState);
        }
        
        private void OnGetCTRTransactionOperationCompleted(object arg) {
            if ((this.GetCTRTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCTRTransactionCompleted(this, new GetCTRTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCTRAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCTRAccount(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr) {
            object[] results = this.Invoke("GetCTRAccount", new object[] {
                        dtFrom,
                        dtTo,
                        strDrCr});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCTRAccountAsync(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr) {
            this.GetCTRAccountAsync(dtFrom, dtTo, strDrCr, null);
        }
        
        /// <remarks/>
        public void GetCTRAccountAsync(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr, object userState) {
            if ((this.GetCTRAccountOperationCompleted == null)) {
                this.GetCTRAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCTRAccountOperationCompleted);
            }
            this.InvokeAsync("GetCTRAccount", new object[] {
                        dtFrom,
                        dtTo,
                        strDrCr}, this.GetCTRAccountOperationCompleted, userState);
        }
        
        private void OnGetCTRAccountOperationCompleted(object arg) {
            if ((this.GetCTRAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCTRAccountCompleted(this, new GetCTRAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCTRAccountDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCTRAccountDetail(string strAccno) {
            object[] results = this.Invoke("GetCTRAccountDetail", new object[] {
                        strAccno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCTRAccountDetailAsync(string strAccno) {
            this.GetCTRAccountDetailAsync(strAccno, null);
        }
        
        /// <remarks/>
        public void GetCTRAccountDetailAsync(string strAccno, object userState) {
            if ((this.GetCTRAccountDetailOperationCompleted == null)) {
                this.GetCTRAccountDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCTRAccountDetailOperationCompleted);
            }
            this.InvokeAsync("GetCTRAccountDetail", new object[] {
                        strAccno}, this.GetCTRAccountDetailOperationCompleted, userState);
        }
        
        private void OnGetCTRAccountDetailOperationCompleted(object arg) {
            if ((this.GetCTRAccountDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCTRAccountDetailCompleted(this, new GetCTRAccountDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCTRSignatoryDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCTRSignatoryDetail(string strAccno) {
            object[] results = this.Invoke("GetCTRSignatoryDetail", new object[] {
                        strAccno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCTRSignatoryDetailAsync(string strAccno) {
            this.GetCTRSignatoryDetailAsync(strAccno, null);
        }
        
        /// <remarks/>
        public void GetCTRSignatoryDetailAsync(string strAccno, object userState) {
            if ((this.GetCTRSignatoryDetailOperationCompleted == null)) {
                this.GetCTRSignatoryDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCTRSignatoryDetailOperationCompleted);
            }
            this.InvokeAsync("GetCTRSignatoryDetail", new object[] {
                        strAccno}, this.GetCTRSignatoryDetailOperationCompleted, userState);
        }
        
        private void OnGetCTRSignatoryDetailOperationCompleted(object arg) {
            if ((this.GetCTRSignatoryDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCTRSignatoryDetailCompleted(this, new GetCTRSignatoryDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCTRIndividualAccDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCTRIndividualAccDetail(string strAccno) {
            object[] results = this.Invoke("GetCTRIndividualAccDetail", new object[] {
                        strAccno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCTRIndividualAccDetailAsync(string strAccno) {
            this.GetCTRIndividualAccDetailAsync(strAccno, null);
        }
        
        /// <remarks/>
        public void GetCTRIndividualAccDetailAsync(string strAccno, object userState) {
            if ((this.GetCTRIndividualAccDetailOperationCompleted == null)) {
                this.GetCTRIndividualAccDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCTRIndividualAccDetailOperationCompleted);
            }
            this.InvokeAsync("GetCTRIndividualAccDetail", new object[] {
                        strAccno}, this.GetCTRIndividualAccDetailOperationCompleted, userState);
        }
        
        private void OnGetCTRIndividualAccDetailOperationCompleted(object arg) {
            if ((this.GetCTRIndividualAccDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCTRIndividualAccDetailCompleted(this, new GetCTRIndividualAccDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBalanceaccsr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetBalanceaccsr(string strAccno, string seqno) {
            object[] results = this.Invoke("GetBalanceaccsr", new object[] {
                        strAccno,
                        seqno});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceaccsrAsync(string strAccno, string seqno) {
            this.GetBalanceaccsrAsync(strAccno, seqno, null);
        }
        
        /// <remarks/>
        public void GetBalanceaccsrAsync(string strAccno, string seqno, object userState) {
            if ((this.GetBalanceaccsrOperationCompleted == null)) {
                this.GetBalanceaccsrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceaccsrOperationCompleted);
            }
            this.InvokeAsync("GetBalanceaccsr", new object[] {
                        strAccno,
                        seqno}, this.GetBalanceaccsrOperationCompleted, userState);
        }
        
        private void OnGetBalanceaccsrOperationCompleted(object arg) {
            if ((this.GetBalanceaccsrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceaccsrCompleted(this, new GetBalanceaccsrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustAccTransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCustAccTransactions(string strAccno, System.DateTime dtFrom, System.DateTime dtTo) {
            object[] results = this.Invoke("GetCustAccTransactions", new object[] {
                        strAccno,
                        dtFrom,
                        dtTo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustAccTransactionsAsync(string strAccno, System.DateTime dtFrom, System.DateTime dtTo) {
            this.GetCustAccTransactionsAsync(strAccno, dtFrom, dtTo, null);
        }
        
        /// <remarks/>
        public void GetCustAccTransactionsAsync(string strAccno, System.DateTime dtFrom, System.DateTime dtTo, object userState) {
            if ((this.GetCustAccTransactionsOperationCompleted == null)) {
                this.GetCustAccTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustAccTransactionsOperationCompleted);
            }
            this.InvokeAsync("GetCustAccTransactions", new object[] {
                        strAccno,
                        dtFrom,
                        dtTo}, this.GetCustAccTransactionsOperationCompleted, userState);
        }
        
        private void OnGetCustAccTransactionsOperationCompleted(object arg) {
            if ((this.GetCustAccTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustAccTransactionsCompleted(this, new GetCustAccTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustAccName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCustAccName(string strAccno) {
            object[] results = this.Invoke("GetCustAccName", new object[] {
                        strAccno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustAccNameAsync(string strAccno) {
            this.GetCustAccNameAsync(strAccno, null);
        }
        
        /// <remarks/>
        public void GetCustAccNameAsync(string strAccno, object userState) {
            if ((this.GetCustAccNameOperationCompleted == null)) {
                this.GetCustAccNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustAccNameOperationCompleted);
            }
            this.InvokeAsync("GetCustAccName", new object[] {
                        strAccno}, this.GetCustAccNameOperationCompleted, userState);
        }
        
        private void OnGetCustAccNameOperationCompleted(object arg) {
            if ((this.GetCustAccNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustAccNameCompleted(this, new GetCustAccNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustAccType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCustAccType(string strAccno) {
            object[] results = this.Invoke("GetCustAccType", new object[] {
                        strAccno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustAccTypeAsync(string strAccno) {
            this.GetCustAccTypeAsync(strAccno, null);
        }
        
        /// <remarks/>
        public void GetCustAccTypeAsync(string strAccno, object userState) {
            if ((this.GetCustAccTypeOperationCompleted == null)) {
                this.GetCustAccTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustAccTypeOperationCompleted);
            }
            this.InvokeAsync("GetCustAccType", new object[] {
                        strAccno}, this.GetCustAccTypeOperationCompleted, userState);
        }
        
        private void OnGetCustAccTypeOperationCompleted(object arg) {
            if ((this.GetCustAccTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustAccTypeCompleted(this, new GetCustAccTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountDetailForBAT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAccountDetailForBAT(string strCurrDate) {
            object[] results = this.Invoke("GetAccountDetailForBAT", new object[] {
                        strCurrDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountDetailForBATAsync(string strCurrDate) {
            this.GetAccountDetailForBATAsync(strCurrDate, null);
        }
        
        /// <remarks/>
        public void GetAccountDetailForBATAsync(string strCurrDate, object userState) {
            if ((this.GetAccountDetailForBATOperationCompleted == null)) {
                this.GetAccountDetailForBATOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountDetailForBATOperationCompleted);
            }
            this.InvokeAsync("GetAccountDetailForBAT", new object[] {
                        strCurrDate}, this.GetAccountDetailForBATOperationCompleted, userState);
        }
        
        private void OnGetAccountDetailForBATOperationCompleted(object arg) {
            if ((this.GetAccountDetailForBATCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountDetailForBATCompleted(this, new GetAccountDetailForBATCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGPData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGPData(string strAccno, System.DateTime dtf, long acentrysrno) {
            object[] results = this.Invoke("GetGPData", new object[] {
                        strAccno,
                        dtf,
                        acentrysrno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGPDataAsync(string strAccno, System.DateTime dtf, long acentrysrno) {
            this.GetGPDataAsync(strAccno, dtf, acentrysrno, null);
        }
        
        /// <remarks/>
        public void GetGPDataAsync(string strAccno, System.DateTime dtf, long acentrysrno, object userState) {
            if ((this.GetGPDataOperationCompleted == null)) {
                this.GetGPDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGPDataOperationCompleted);
            }
            this.InvokeAsync("GetGPData", new object[] {
                        strAccno,
                        dtf,
                        acentrysrno}, this.GetGPDataOperationCompleted, userState);
        }
        
        private void OnGetGPDataOperationCompleted(object arg) {
            if ((this.GetGPDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGPDataCompleted(this, new GetGPDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGPDataAcc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGPDataAcc(string strAccno, System.DateTime dtf) {
            object[] results = this.Invoke("GetGPDataAcc", new object[] {
                        strAccno,
                        dtf});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGPDataAccAsync(string strAccno, System.DateTime dtf) {
            this.GetGPDataAccAsync(strAccno, dtf, null);
        }
        
        /// <remarks/>
        public void GetGPDataAccAsync(string strAccno, System.DateTime dtf, object userState) {
            if ((this.GetGPDataAccOperationCompleted == null)) {
                this.GetGPDataAccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGPDataAccOperationCompleted);
            }
            this.InvokeAsync("GetGPDataAcc", new object[] {
                        strAccno,
                        dtf}, this.GetGPDataAccOperationCompleted, userState);
        }
        
        private void OnGetGPDataAccOperationCompleted(object arg) {
            if ((this.GetGPDataAccCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGPDataAccCompleted(this, new GetGPDataAccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCCardDetailCompletedEventHandler(object sender, GetCCardDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCCardDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCCardDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetLankaBanglaFCompletedEventHandler(object sender, GetLankaBanglaFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLankaBanglaFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLankaBanglaFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetLankaBanglaFDateRangeCompletedEventHandler(object sender, GetLankaBanglaFDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLankaBanglaFDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLankaBanglaFDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetRateCompletedEventHandler(object sender, GetRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetHBInfoCompletedEventHandler(object sender, GetHBInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHBInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHBInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetLankaBanglaFVisaCompletedEventHandler(object sender, GetLankaBanglaFVisaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLankaBanglaFVisaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLankaBanglaFVisaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetLankaBanglaFMoneyCompletedEventHandler(object sender, GetLankaBanglaFMoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLankaBanglaFMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLankaBanglaFMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetONEBankVisaCompletedEventHandler(object sender, GetONEBankVisaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetONEBankVisaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetONEBankVisaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetRJSCTranCompletedEventHandler(object sender, GetRJSCTranCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRJSCTranCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRJSCTranCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetRJSCTranDateRangeCompletedEventHandler(object sender, GetRJSCTranDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRJSCTranDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRJSCTranDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetRJSCTranDateRangeNewCompletedEventHandler(object sender, GetRJSCTranDateRangeNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRJSCTranDateRangeNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRJSCTranDateRangeNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetLCARTranCompletedEventHandler(object sender, GetLCARTranCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLCARTranCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLCARTranCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetLCMasterCompletedEventHandler(object sender, GetLCMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLCMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLCMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCifsDetailCompletedEventHandler(object sender, GetCifsDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCifsDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCifsDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetPHTranCompletedEventHandler(object sender, GetPHTranCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPHTranCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPHTranCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCTRTransactionCompletedEventHandler(object sender, GetCTRTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCTRTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCTRTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCTRAccountCompletedEventHandler(object sender, GetCTRAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCTRAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCTRAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCTRAccountDetailCompletedEventHandler(object sender, GetCTRAccountDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCTRAccountDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCTRAccountDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCTRSignatoryDetailCompletedEventHandler(object sender, GetCTRSignatoryDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCTRSignatoryDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCTRSignatoryDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCTRIndividualAccDetailCompletedEventHandler(object sender, GetCTRIndividualAccDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCTRIndividualAccDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCTRIndividualAccDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetBalanceaccsrCompletedEventHandler(object sender, GetBalanceaccsrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceaccsrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceaccsrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCustAccTransactionsCompletedEventHandler(object sender, GetCustAccTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustAccTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustAccTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCustAccNameCompletedEventHandler(object sender, GetCustAccNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustAccNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustAccNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCustAccTypeCompletedEventHandler(object sender, GetCustAccTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustAccTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustAccTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetAccountDetailForBATCompletedEventHandler(object sender, GetAccountDetailForBATCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountDetailForBATCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountDetailForBATCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetGPDataCompletedEventHandler(object sender, GetGPDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGPDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGPDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetGPDataAccCompletedEventHandler(object sender, GetGPDataAccCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGPDataAccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGPDataAccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591